export enum ErrorCodeEnum {
  ERR_INTERNAL = 'ERR_INTERNAL',
  ERR_VALIDATION = 'ERR_VALIDATION',
  ERR_NO_PARAMS = 'ERR_NO_PARAMS',
  ERR_NOT_FOUND = 'ERR_NOT_FOUND',
  ERR_CONFLICT = 'ERR_CONFLICT',
}
